// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ11jMh2B5nx1KHtCoLSj2O7JbvegKrbA',
    appId: '1:123385729636:web:5a3e8fb60df7583f9cc571',
    messagingSenderId: '123385729636',
    projectId: 'apdev-starer',
    authDomain: 'apdev-starer.firebaseapp.com',
    storageBucket: 'apdev-starer.firebasestorage.app',
    measurementId: 'G-X5MMGFXB7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgUip5FCH_uCZwQ6VLg_hlhDpjpRDan8Q',
    appId: '1:123385729636:android:bd7604e5822eb0329cc571',
    messagingSenderId: '123385729636',
    projectId: 'apdev-starer',
    storageBucket: 'apdev-starer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZcKeO4JfkTs8fzU675MEm95pTHEJoxY',
    appId: '1:123385729636:ios:0836c9a07c6aa7359cc571',
    messagingSenderId: '123385729636',
    projectId: 'apdev-starer',
    storageBucket: 'apdev-starer.firebasestorage.app',
    iosBundleId: 'com.apdev.starter.starterProject',
  );
}
